version: "3.8"

services:
  backend:
    build:
      context: ./server          # ðŸ”¥ FIX
      dockerfile: Dockerfile
    container_name: shopzilla-backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shopzilla-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://backend:5000
    depends_on:
      - backend
